### ISSUE TITLE
Pagamento

### ISSUE THREAD

**Issue by DanielScapulatempo** [fernandomacoli/laravel-moip-recorrente#1]
Olá,

Tentei realizar o processo de assinatura, porém ele solicita do código de segurança do cartão.
Qual seria a forma correta de enviar para a API ?

Tentei inserir uma um valor com chave CVC dentro de credit_card, porém não obtive sucesso.

Poderia me auxiliar, por favor ?

**Comment by fernandomacoli** [comment]
Olá, o este pacote foi um clone de outro pois precisei fazer algumas alterações pessoais, acesse o pacote original https://github.com/endsalone/laravel-moip-recorrente pois tem um wiki que pode lhe ajudar, mas vamos lá mesmo no pacote original não precisa se passar o CVC.
No link que lhe informei acima vá na parte de assinaturas.
Já lhe adianto uma coisa, quando for fazer o envio dos dados precisa passar o Code que é um código particular seu, mas por algum motivo depois não consegue se resgatar a assinatura ou assinante por este código, consegui resolver passando mais um atributo, ficando assim

  $data = [
                **"ownId"=> $ownid,**
                "code"=> $ownid,
                "email"=> $pessoa_dados['email'],
                "fullname"=> $pessoa->nome,
                "cpf"=> $cpf_documento,
                "phone_area_code"=> $fone_ddd,
                "phone_number"=> $fone_num,
                "birthdate_day"=> $aniversario_dia,
                "birthdate_month"=> $aniversario_mes,
                "birthdate_year"=> $aniversario_ano,
                "address" => [
                        "street"=> $logradouro->nome,
                        "number"=> $logradouro->numero,
                        "complement"=> $logradouro->complemento,
                        "district"=> $logradouro->bairro,
                        "city"=> $logradouro->cidade,
                        "state"=> $logradouro->estado,
                        "country"=> $pais,
                        "zipcode"=> $cep
                ],
                "billing_info"=> [
                    "credit_card"=> [
                            "holder_name"=> $pessoa_dados['nome'],
                            "number"=> $pessoa_dados['numero_cartao'],
                            "expiration_month"=>  $card_mes_venc,
                            "expiration_year"=> $card_ano_venc
                    ]
                ]
            ];

Uma outra coisa, mesmo passando os dados de pgto no momento da criação da assinatura eles não são salvos então tive que resgatar os dados da assinatura e depois atualizar os dados de pgto.

**Comment by DanielScapulatempo** [comment]
@fernandomacoli 
Perfeito ! Muito obrigado pelo auxílio. Deu tudo certo. 

Sobre o problema que tinha com o CVC,era na própria Wirecard. Precisaram fazer uma liberação por lá.

A parte dos dados de pagamento, foi a parte mais chata de se fazer mesmo. Mas resolvi criando o usuário e após a criação, inserindo os dados de cobrança com a função editBillingInfo.

Feito isso, prossegui com a emissão do pagamento e deu certo.

Agradeço pela atenção.
